# Generated by Django 4.2.6 on 2023-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_customdoctor_heure_remove_jour_docteurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jouretheure',
            name='heure',
        ),
        migrations.RemoveField(
            model_name='jouretheure',
            name='jours',
        ),
        migrations.RemoveField(
            model_name='jouretheure',
            name='modele',
        ),
        migrations.RemoveField(
            model_name='customdoctor',
            name='jours_disponibles',
        ),
        migrations.AddField(
            model_name='customdoctor',
            name='heure',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='customdoctor',
            name='jours',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='maimouna', max_length=10),
        ),
        migrations.DeleteModel(
            name='Heure',
        ),
        migrations.DeleteModel(
            name='Jour',
        ),
        migrations.DeleteModel(
            name='JourEtHeure',
        ),
    ]
