# Generated by Django 4.2.6 on 2023-10-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doctor', '0004_alter_customdoctor_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdoctor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_doctors', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customdoctor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_doctors', to='auth.permission'),
        ),
    ]
