# Generated by Django 4.2.6 on 2023-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doctor', '0005_alter_customdoctor_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdoctor',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customdoctor',
            name='groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='custom_doctors', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customdoctor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, editable=False, related_name='custom_doctors', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='customdoctor',
            name='experience_new',
            field=models.IntegerField(default=0, null=True, blank=True),
        ),
    ]
