# Generated by Django 4.2.6 on 2023-10-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_customdoctor_experience_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdoctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
