# Generated by Django 4.2.6 on 2023-10-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_customdoctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10)),
                ('heure_debut', models.TimeField(default='00:00')),
                ('heure_fin', models.TimeField(default='00:00')),
            ],
        ),
        migrations.RemoveField(
            model_name='customdoctor',
            name='jours',
        ),
        migrations.AddField(
            model_name='customdoctor',
            name='jours',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctor.jour_doctor'),
        ),
    ]
