# Generated by Django 4.2.6 on 2023-10-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_customdoctor_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdoctor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customdoctor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customdoctor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customdoctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customdoctor',
            name='user_permissions',
        ),
    ]
