# Generated by Django 4.2.6 on 2023-10-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_customdoctor_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdoctor',
            name='heure',
        ),
    ]
