# Generated by Django 4.2.6 on 2023-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_remove_customdoctor_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdoctor',
            name='jours',
            field=models.ManyToManyField(blank=True, to='doctor.jour_doctor'),
        ),
    ]
