# Generated by Django 4.2.6 on 2023-10-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_first_name_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agree',
            field=models.BooleanField(default=True),
        ),
    ]
