# Generated by Django 4.2.6 on 2023-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitale', '0002_remove_customhopitale_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customhopitale',
            name='heure',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='jour_hopitale',
            name='heure_debut',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='jour_hopitale',
            name='heure_fin',
            field=models.TimeField(default='00:00'),
        ),
    ]
