# Generated by Django 4.2.6 on 2023-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitale', '0005_alter_customhopitale_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customhopitale',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customhopitale',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customhopitale',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customhopitale',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customhopitale',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='customhopitale',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='customhopitale',
            name='specialists',
            field=models.ManyToManyField(blank=True, to='hopitale.specialist'),
        ),
    ]
