# Generated by Django 4.2.6 on 2023-10-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopitale', '0006_specialist_remove_customhopitale_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customhopitale',
            old_name='specialists',
            new_name='specialist',
        ),
    ]
