# Generated by Django 4.2.6 on 2023-10-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Rendez_Vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name_medecin', models.CharField(blank=True, max_length=255, null=True)),
                ('profession_medecin', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_medcin', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(blank=True, default='00:00', null=True)),
                ('duree', models.CharField(choices=[('30 minute', '30 minute'), ('1 heure', '1 heure'), ('1 heure 30 minute', '1h 30 minute'), ('2 heure', '2 heure')], max_length=50)),
                ('package', models.CharField(choices=[('Messaging', 'Messaging'), ('Voice Call', 'Voice Call'), ('Video Call', 'Video Call'), ('In Person', 'In Person')], max_length=50)),
                ('amount', models.IntegerField(choices=[(20, 20), (40, 40), (60, 60), (100, 100)])),
                ('booking', models.CharField(choices=[('Self', 'Self'), ('Other', 'Other')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('probleme', models.CharField(blank=True, max_length=255, null=True)),
                ('payement', models.CharField(choices=[('Paypal', 'Paypal'), ('Apple Pay', 'Apple Pay')], max_length=50)),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.IntegerField(unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('cvv', models.IntegerField(unique=True)),
                ('save', models.BooleanField(default=True)),
                ('cash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, editable=False, related_name='custom_rendez_vous', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, editable=False, related_name='custom_rendez_vous', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
