# Generated by Django 4.2.6 on 2023-10-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rendez_vous', '0002_alter_custom_rendez_vous_card_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custom_Rendez_Vous',
            new_name='CustomRendezVous',
        ),
    ]
