# Generated by Django 4.2.6 on 2023-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0003_rename_custom_rendez_vous_customrendezvous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendezvous',
            name='card_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='cvv',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
