# Generated by Django 4.2.6 on 2023-10-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0004_alter_customrendezvous_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendezvous',
            name='cvv',
            field=models.IntegerField(max_length=4, unique=True),
        ),
    ]
