# Generated by Django 4.2.6 on 2023-10-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0005_alter_customrendezvous_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendezvous',
            name='cvv',
            field=models.IntegerField(unique=True),
        ),
    ]
