# Generated by Django 4.2.6 on 2023-10-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0007_alter_customrendezvous_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendezvous',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='password',
        ),
    ]
