# Generated by Django 4.2.6 on 2023-10-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0008_remove_customrendezvous_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendezvous',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='user_permissions',
        ),
    ]
