# Generated by Django 4.2.6 on 2023-10-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0009_remove_customrendezvous_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendezvous',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='heure',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='package',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='payement',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='probleme',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='save',
        ),
    ]
