# Generated by Django 4.2.6 on 2023-10-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0010_remove_customrendezvous_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrendezvous',
            name='amount',
            field=models.IntegerField(choices=[(20, 20), (40, 40), (60, 60), (100, 100)], default=20),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='date',
            field=models.DateField(blank=True, default='2023-10-10', null=True),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='duree',
            field=models.CharField(choices=[('30 minute', '30 minute'), ('1 heure', '1 heure'), ('1 heure 30 minute', '1h 30 minute'), ('2 heure', '2 heure')], default='30 minute', max_length=50),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='heure',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='package',
            field=models.CharField(choices=[('Messaging', 'Messaging'), ('Voice Call', 'Voice Call'), ('Video Call', 'Video Call'), ('In Person', 'In Person')], default='Messaging', max_length=50),
        ),
    ]
