# Generated by Django 4.2.6 on 2023-10-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0011_customrendezvous_amount_customrendezvous_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrendezvous',
            name='age',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='booking',
            field=models.CharField(choices=[('Self', 'Self'), ('Other', 'Other')], default='Self', max_length=50),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='payement',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Apple Pay', 'Apple Pay')], default='Paypal', max_length=50),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='probleme',
            field=models.CharField(blank=True, default='bonjour', null=True),
        ),
    ]
