# Generated by Django 4.2.6 on 2023-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0012_customrendezvous_age_customrendezvous_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrendezvous',
            name='card_name',
            field=models.CharField(default='mai', max_length=255),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='card_number',
            field=models.IntegerField(default=23456),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='cvv',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='expiry_date',
            field=models.DateField(default='2023-10-10'),
        ),
    ]
