# Generated by Django 4.2.6 on 2023-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0013_customrendezvous_card_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrendezvous',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='save',
            field=models.BooleanField(default=True),
        ),
    ]
