# Generated by Django 4.2.6 on 2023-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0014_customrendezvous_cash_customrendezvous_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendezvous',
            name='cash',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='save',
            field=models.BooleanField(),
        ),
    ]
