# Generated by Django 4.2.6 on 2023-10-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0015_alter_customrendezvous_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendezvous',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='save',
        ),
    ]
