# Generated by Django 4.2.6 on 2023-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0018_alter_customrendezvous_cash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customrendezvous',
            old_name='adresse_medcin',
            new_name='adresse_medecin',
        ),
        migrations.RenameField(
            model_name='customrendezvous',
            old_name='payement',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='customrendezvous',
            name='save',
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='cash_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customrendezvous',
            name='save_to_database',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='amount',
            field=models.IntegerField(choices=[(20, '20'), (40, '40'), (60, '60'), (100, '100')], default=20),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='duree',
            field=models.CharField(choices=[('30 minutes', '30 minutes'), ('1 heure', '1 heure'), ('1 heure 30 minutes', '1 heure 30 minutes'), ('2 heures', '2 heures')], default='30 minutes', max_length=50),
        ),
    ]
