# Generated by Django 4.2.6 on 2023-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0019_rename_adresse_medcin_customrendezvous_adresse_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendezvous',
            name='card_name',
            field=models.CharField(blank=True, default='mai', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='card_number',
            field=models.IntegerField(blank=True, default=23456, null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='cash_payment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='cvv',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='expiry_date',
            field=models.DateField(blank=True, default='2023-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='payment',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Apple Pay', 'Apple Pay')], default='Paypal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='save_to_database',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
