# Generated by Django 4.2.6 on 2023-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0020_alter_customrendezvous_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendezvous',
            name='card_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='card_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='cvv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='expiry_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customrendezvous',
            name='payment',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Apple Pay', 'Apple Pay')], default='', max_length=50, null=True),
        ),
    ]
