# Generated by Django 4.2.6 on 2023-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0022_carte_remove_customrendezvous_card_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrendezvous',
            name='carte',
            field=models.ManyToManyField(blank=True, null=True, to='rendez_vous.carte'),
        ),
    ]
