# Generated by Django 4.2.6 on 2023-10-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0023_customrendezvous_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrendezvous',
            name='carte',
            field=models.ManyToManyField(blank=True, to='rendez_vous.carte'),
        ),
    ]
