# Generated by Django 4.2.6 on 2023-10-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0024_alter_customrendezvous_carte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendezvous',
            name='carte',
        ),
    ]
