# Generated by Django 4.2.6 on 2023-10-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0025_remove_customrendezvous_carte'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrendezvous',
            name='carte',
            field=models.ManyToManyField(blank=True, to='rendez_vous.carte'),
        ),
    ]
