# Generated by Django 4.2.6 on 2023-10-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0027_carte_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='card_name',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
