# Generated by Django 4.2.6 on 2023-10-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0028_alter_carte_card_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='users',
        ),
    ]
