# Generated by Django 4.2.6 on 2023-11-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0029_remove_carte_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='expiry_date',
            field=models.DateField(blank=True, default='YY-MM', null=True),
        ),
    ]
