# Generated by Django 4.2.6 on 2023-11-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0030_alter_carte_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendezvous',
            name='carte',
        ),
    ]
